"""Inital Migration

Revision ID: 5a8277914ef0
Revises: 
Create Date: 2022-04-12 11:53:03.124221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8277914ef0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('cafe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(length=250), nullable=False),
    sa.Column('map_url', sa.TEXT(length=500), nullable=False),
    sa.Column('img_url', sa.TEXT(length=500), nullable=False),
    sa.Column('location', sa.TEXT(length=250), nullable=False),
    sa.Column('has_sockets', sa.BOOLEAN(), nullable=False),
    sa.Column('has_toilet', sa.BOOLEAN(), nullable=False),
    sa.Column('has_wifi', sa.BOOLEAN(), nullable=False),
    sa.Column('can_take_calls', sa.BOOLEAN(), nullable=False),
    sa.Column('seats', sa.TEXT(length=250), nullable=True),
    sa.Column('coffee_price', sa.TEXT(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
